import _EventsList from './EventsList';
import _Start from './Start';
import _Profile from './Profile';
import _Images from './Images';
import _EditProfile from './EditProfile';
import _Chat from './Chat';
import _Groups from './Groups';
import _Expenses from './Expenses';
import _ChatMessages from './ChatMessages';
import _Preferences from './Preferences';
import _Insights from './Insights';
import _VerifyAccount from './VerifyAccount';
import _EventsOnMonth from './EventsOnMonth';
import _GroupMembers from './GroupMembers';
import _ChangePassword from './ChangePassword';
import _UpdateUserForm from './UpdateUserForm';
import _CreatePost from './CreatePost';
import _PostDetails from './PostDetails';
import _PersonalDetails from './PersonalDetails';

export const EventsList = _EventsList;
export const Start = _Start;
export const Profile = _Profile;
export const Images = _Images;
export const EditProfile = _EditProfile;
export const Chat = _Chat;
export const Groups = _Groups;
export const Expenses = _Expenses;
export const ChatMessages = _ChatMessages;
export const Preferences = _Preferences;
export const Insights = _Insights;
export const VerifyAccount = _VerifyAccount;
export const EventsOnMonth = _EventsOnMonth;
export const ChangePassword = _ChangePassword;
export const GroupMembers = _GroupMembers;
export const UpdateUserForm = _UpdateUserForm;
export const CreatePost = _CreatePost;
export const PostDetails = _PostDetails;
export const PersonalDetails = _PersonalDetails;
